"""Comparative disability and incapacity definitions for the library.

Sourced from a multi-context reference dashboard. Personal-case mapping
has been removed. Family law, criminal capacity, tax rebate, education,
and empty statutory-placeholder rows were culled.
"""

from __future__ import annotations

DEFINITIONS: list[dict] = [
    {
        'kind': "disability",
        'context': "General / Dictionary",
        'term': "Disability",
        'slug': "disability-general-dictionary-disability",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "A physical/mental condition limiting activities; lack of ability; a handicap preventing normal life or work.",
        'condition': "Any condition, injury, or limitation, however defined",
        'functional_status': "A visible or assumed reduction in doing an everyday activity",
        'applied_test': "Purely descriptive - no formal test applied",
        'severity': "Mild, moderate, severe",
        'duration': "Temporary, chronic, permanent",
        'scope': "Partial vs. Total",
        'other': "Colloquial, non-technical usage",
        'impact': "Negatively affects basic self-care, mobility, communication, or work.",
        'assessment_basis': "Aids/meds are seen as mitigating the visible impact (e.g. \"with glasses, they function normally\"), so the negative effect is usually judged in the mitigated state.",
        'example': "Someone says \"he's disabled\" about a person who uses a wheelchair, without reference to any legal test.",
        'source': "General English usage",
    },
    {
        'kind': "disability",
        'context': "General / Dictionary",
        'term': "Disablement",
        'slug': "disability-general-dictionary-disablement",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "The state or process of being disabled; the act of making a person or device inoperative.",
        'condition': "An accident, illness, or device fault has occurred",
        'functional_status': "Ability to do routine tasks is reduced",
        'applied_test': "No formal test - informal, ongoing observation",
        'severity': "N/A",
        'duration': "Temporary vs. permanent",
        'scope': "Partial vs. Total",
        'other': "Accidental, developmental, deliberate cause",
        'impact': "Progressive reduction in ability to perform routine tasks.",
        'assessment_basis': "Aids/meds may slow or halt the progression, but general use does not strictly exclude them.",
        'example': "\"The stroke resulted in his gradual disablement over several months.\"",
        'source': "General English usage",
    },
    {
        'kind': "disability",
        'context': "Medical Model",
        'term': "Disability",
        'slug': "disability-medical-model-disability",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "A biological defect, pathology, or bodily system failure requiring treatment/cure.",
        'condition': "A diagnosed biological/medical pathology exists",
        'functional_status': "Activities of Daily Living (eating, bathing, mobility) are impaired",
        'applied_test': "Function measured clinically, both untreated and \"optimized\" (treated)",
        'severity': "Clinical scales, mild to profound",
        'duration': "Acute vs. Chronic",
        'scope': "Quantified as % functional loss",
        'other': "Diagnosis-driven, treatment-oriented",
        'impact': "Impairs Activities of Daily Living (ADLs) like eating, bathing, toileting.",
        'assessment_basis': "Often assessed without aids/meds to gauge the pure underlying pathology; doctors also separately assess \"optimized\" function to measure treatment efficacy.",
        'example': "A neurologist rates baseline motor function before and after Parkinson's medication to measure drug efficacy.",
        'source': "Clinical/medical practice",
    },
    {
        'kind': "disability",
        'context': "Medical Model",
        'term': "Disablement",
        'slug': "disability-medical-model-disablement",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "The pathological outcome of injury/disease.",
        'condition': "Injury/disease has occurred and is being treated",
        'functional_status': "Physiological capacity is reduced",
        'applied_test': "Measured at Maximum Medical Improvement (MMI) - the stable post-treatment plateau",
        'severity': "Mirrors medical disability qualifiers",
        'duration': "Acute vs. Chronic",
        'scope': "Mirrors medical disability qualifiers",
        'other': "Point of Maximum Medical Improvement (MMI)",
        'impact': "Loss of physiological capacity.",
        'assessment_basis': "Typically measured at MMI, both with and without current treatments.",
        'example': "A spinal injury patient is assessed at MMI, 18 months post-surgery, for residual physiological loss.",
        'source': "Clinical/medical practice",
    },
    {
        'kind': "disability",
        'context': "Social Model",
        'term': "Disability",
        'slug': "disability-social-model-disability",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "Disadvantage imposed by societal barriers excluding people with impairments.",
        'condition': "A physical/mental impairment exists (not in dispute)",
        'functional_status': "Barriers (buildings, attitudes, policy) block participation",
        'applied_test': "Never assessed via medication - only via the environment's inclusiveness",
        'severity': "Intensity of environmental barriers",
        'duration': "N/A",
        'scope': "N/A",
        'other': "Accessible vs. inaccessible society",
        'impact': "The negative effect is caused by inaccessible buildings, attitudes, and policies, not the impairment itself.",
        'assessment_basis': "Aids/meds are irrelevant; disability is defined by social exclusion, not by whether medication reduces symptoms.",
        'example': "A wheelchair user is \"disabled\" by a building with no ramp, not by the impairment itself.",
        'source': "Disability studies / social theory",
    },
    {
        'kind': "disability",
        'context': "Social Model",
        'term': "Disablement",
        'slug': "disability-social-model-disablement",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "The active process of being marginalized by societal structures.",
        'condition': "A structural/attitudinal exclusion process begins",
        'functional_status': "Social participation is progressively restricted",
        'applied_test': "Measured by number/severity of barriers encountered, not medical treatment",
        'severity': "Degree of systemic discrimination",
        'duration': "Gradual vs. sudden exclusion",
        'scope': "N/A",
        'other': "N/A",
        'impact': "Progressive restriction of social participation.",
        'assessment_basis': "Measured by the number and severity of barriers encountered, not by medical aids.",
        'example': "A visually impaired employee is gradually disablement-ed by a workplace that keeps switching to inaccessible software.",
        'source': "Disability studies / social theory",
    },
    {
        'kind': "disability",
        'context': "Biopsychosocial (WHO-ICF)",
        'term': "Disability",
        'slug': "disability-biopsychosocial-who-icf-disability",
        'family': "model",
        'jurisdictions': ['comparative'],
        'definition': "Umbrella term for impairments, activity limitations, and participation restrictions.",
        'condition': "An impairment (body function/structure) is present",
        'functional_status': "Activity Limitations - can the task be done at all?",
        'applied_test': "Two scores: Capacity (unaided, standardised setting) vs Performance (aided, real-world)",
        'severity': "ICF Qualifiers 0-4 (0=None, 4=Complete)",
        'duration': "Episodic, stable, fluctuating",
        'scope': "With/without devices (Capacity vs. Performance)",
        'other': "Two-axis assessment model",
        'impact': "Defined as Activity Limitations (difficulty executing tasks) and Participation Restrictions (problems in life situations).",
        'assessment_basis': "ICF uses two distinct ratings: (1) Capacity - what they can do without aids/assistance in a standardized environment; (2) Performance - what they actually do with aids/meds in their real environment.",
        'example': "A person's ICF profile records \"Capacity: severe difficulty walking\" but \"Performance: mild difficulty\" once a prosthetic is factored in.",
        'source': "WHO International Classification of Functioning, Disability and Health (ICF)",
    },
    {
        'kind': "disability",
        'context': "Legal - USA (ADA)",
        'term': "Disability",
        'slug': "disability-legal-usa-ada-disability",
        'family': "legal",
        'jurisdictions': ['comparative'],
        'definition': "Impairment substantially limiting one or more major life activities; or a record of, or being regarded as having, such an impairment.",
        'condition': "A physical/mental impairment exists",
        'functional_status': "A major life activity is substantially limited",
        'applied_test': "Tested WITHOUT mitigating measures (meds, prosthetics) - except ordinary glasses",
        'severity': "\"Substantially limits\" = significant restriction vs. average person",
        'duration': "Long-term (>=6 months in some rulings)",
        'scope': "Major life activities (self-care, walking, seeing, hearing, breathing, learning, working)",
        'other': "Eyeglasses/contact lenses excepted",
        'impact': "Affects Major Life Activities.",
        'assessment_basis': "Under the ADAAA (2008), mitigating measures (medications, prosthetics, hearing aids, assistive tech) are generally NOT considered when assessing the limitation. The only exception is ordinary eyeglasses/contact lenses - assessed in the unmitigated state, similar to the UK rule.",
        'example': "An employee with controlled epilepsy is still \"disabled\" under the ADA even though medication controls the seizures.",
        'source': "Americans with Disabilities Act, as amended (ADAAA 2008)",
    },
    {
        'kind': "disability",
        'context': "Legal - UK (Equality Act 2010)",
        'term': "Disability",
        'slug': "disability-legal-uk-equality-act-2010-disability",
        'family': "legal",
        'jurisdictions': ['comparative'],
        'definition': "Physical/mental impairment with a substantial, long-term negative effect on normal daily activities.",
        'condition': "A physical/mental impairment exists",
        'functional_status': "A normal daily activity is substantially, long-term affected",
        'applied_test': "Tested WITHOUT medication or aids - imagine the person untreated",
        'severity': "\"Substantial\" = more than minor/trivial",
        'duration': "\">=12 months or for life\"",
        'scope': "Normal daily activities (mobility, manual dexterity, coordination, continence, ability to lift/carry)",
        'other': "Assessed without aids",
        'impact': "Negatively affects \"normal daily activities\".",
        'assessment_basis': "Assessed without accounting for medication or aids (e.g. prostheses, hearing aids, oxygen therapy) - you must imagine the person without their treatment or equipment.",
        'example': "A diabetic whose condition is fully controlled by insulin is still legally \"disabled\", because the assessment ignores the insulin's effect.",
        'source': "Equality Act 2010 (UK), Schedule 1",
    },
    {
        'kind': "disability",
        'context': "Legal - UK (Equality Act 2010)",
        'term': "Disablement",
        'slug': "disability-legal-uk-equality-act-2010-disablement",
        'family': "legal",
        'jurisdictions': ['comparative'],
        'definition': "(Police/employment law) Being blind, deaf, or permanently handicapped.",
        'condition': "Blindness, deafness, or permanent handicap is present",
        'functional_status': "Ability to perform statutory duties (e.g. policing) is affected",
        'applied_test': "Assessed on the raw, untreated condition",
        'severity': "N/A",
        'duration': "Permanent vs. Temporary",
        'scope': "Substantial vs. non-substantial handicap",
        'other': "Sector-specific (e.g. police)",
        'impact': "Affects ability to perform specific statutory duties (e.g. police work).",
        'assessment_basis': "Tends to follow the same rule as the Equality Act - assessed on the raw condition, not the mitigated state.",
        'example': "A police officer's fitness board assesses hearing loss without factoring in a hearing aid.",
        'source': "UK police/employment regulations",
    },
    {
        'kind': "disability",
        'context': "Legal - Australia (DDA 1992)",
        'term': "Disability",
        'slug': "disability-legal-australia-dda-1992-disability",
        'family': "legal",
        'jurisdictions': ['au'],
        'definition': "Total/partial loss of bodily/mental functions; loss of a body part; presence of disease organisms in the body.",
        'condition': "Loss of bodily/mental function, or a disease organism is present",
        'functional_status': "Normal life activities are affected",
        'applied_test': "No mandated \"without aids\" rule - tribunals look at the actual functional limitation",
        'severity': "N/A",
        'duration': "Past, present, or imputed (future/perceived)",
        'scope': "Total vs. Partial loss; physical, intellectual, psychiatric, sensory",
        'other': "Broadest statutory definition of the jurisdictions covered",
        'impact': "Loss or impairment of a bodily or mental function affecting normal life.",
        'assessment_basis': "The DDA does not statutorily mandate a \"without aids\" rule. Tribunals generally look at the actual functional limitation, but case law often considers the inherent condition rather than the mitigated one for discrimination purposes.",
        'example': "A job applicant with HIV (an asymptomatic \"disease organism\" present in the body) is covered by the DDA even without symptoms.",
        'source': "Disability Discrimination Act 1992 (Cth), s.4",
    },
    {
        'kind': "disability",
        'context': "Legal - Australia (DDA 1992)",
        'term': "Disablement",
        'slug': "disability-legal-australia-dda-1992-disablement",
        'family': "legal",
        'jurisdictions': ['au'],
        'definition': "(Not a defined statutory term)",
        'condition': "N/A",
        'functional_status': "N/A",
        'applied_test': "N/A",
        'severity': "N/A",
        'duration': "N/A",
        'scope': "N/A",
        'other': "N/A",
        'impact': "N/A",
        'assessment_basis': "N/A",
        'example': "N/A",
        'source': "Disability Discrimination Act 1992 (Cth)",
    },
    {
        'kind': "disability",
        'context': "Legal - South Africa (Employment Equity Act 55 of 1998)",
        'term': "Disability",
        'slug': "disability-legal-south-africa-employment-equity-act-55-of-1998-disability",
        'family': "employment",
        'jurisdictions': ['za'],
        'definition': "Long-term or recurring physical or mental impairment that substantially limits prospects of entry into, or advancement in, employment.",
        'condition': "A long-term or recurring impairment exists",
        'functional_status': "Prospects of entry into or advancement in employment are limited",
        'applied_test': "Code of Good Practice generally looks at the unmitigated baseline",
        'severity': "Substantial limitation on prospects of entry/advancement",
        'duration': "Long-term or recurring (Code of Good Practice: normally >=12 months)",
        'scope': "Prospects of entry into, or advancement in, employment",
        'other': "Guided by the EEA Code of Good Practice on Disability",
        'impact': "Affects ability to be employed, retained, or promoted on an equal basis with non-disabled colleagues.",
        'assessment_basis': "medication, prosthetics) into account, broadly aligned with the UK/ADA unmitigated-state approach, though this is guidance rather than a hard statutory rule as in the UK.",
        'example': "An applicant with a controlled psychiatric condition is still classified as \"disabled\" for EEA reporting/reasonable-accommodation purposes.",
        'source': "Employment Equity Act 55 of 1998 (South Africa) + EEA Code of Good Practice on Disability",
    },
    {
        'kind': "disability",
        'context': "Legal - South Africa (Employment Equity Act 55 of 1998)",
        'term': "Disablement",
        'slug': "disability-legal-south-africa-employment-equity-act-55-of-1998-disablement",
        'family': "employment",
        'jurisdictions': ['za'],
        'definition': "(Not a separately defined statutory term; \"disability\" is the operative term)",
        'condition': "N/A",
        'functional_status': "N/A",
        'applied_test': "N/A",
        'severity': "N/A",
        'duration': "N/A",
        'scope': "N/A",
        'other': "N/A",
        'impact': "N/A",
        'assessment_basis': "N/A",
        'example': "N/A",
        'source': "Employment Equity Act 55 of 1998 (South Africa)",
    },
    {
        'kind': "disability",
        'context': "Compensation - South Africa (COIDA)",
        'term': "Disability / Disablement",
        'slug': "disability-compensation-south-africa-coida-disability-disablement",
        'family': "compensation",
        'jurisdictions': ['za'],
        'definition': "Permanent or temporary reduction in earning capacity resulting from an occupational injury or disease.",
        'condition': "An occupational injury or disease has occurred",
        'functional_status': "Earning capacity in the pre-injury job is reduced",
        'applied_test': "Rated as a fixed statutory percentage once stabilised (post-MMI)",
        'severity': "Percentage of permanent disablement, per statutory schedule (e.g. loss of a limb rated at a fixed %)",
        'duration': "Temporary Total (TTD) vs. Permanent Disablement (PD)",
        'scope': "Whole-body vs. scheduled body-part impairment",
        'other': "Compensation Commissioner determines the % via a medical report",
        'impact': "Reduces or eliminates the ability to earn wages in the pre-injury occupation.",
        'assessment_basis': "Assessed after medical treatment has stabilised the condition (i.e. at MMI); the statutory % disablement rating already reflects the residual, post-treatment state, so it is effectively assessed in the mitigated state.",
        'example': "A factory worker who loses a hand is assessed by the Compensation Commissioner at a fixed statutory percentage of permanent disablement, triggering a lump-sum or pension payout.",
        'source': "Compensation for Occupational Injuries and Diseases Act 130 of 1993 (COIDA)",
    },
    {
        'kind': "disability",
        'context': "Insurance - South Africa (Income Protection / ASISA)",
        'term': "Disability",
        'slug': "disability-insurance-south-africa-income-protection-asisa-disability",
        'family': "insurance",
        'jurisdictions': ['za'],
        'definition': "Inability to perform the material and substantial duties of one's own occupation (or, later, any occupation for which reasonably suited), triggering income-replacement benefits.",
        'condition': "Illness or injury exists (medically diagnosed)",
        'functional_status': "Material/substantial job duties (or any suitable job's duties) can't be performed",
        'applied_test': "Tested WITH treatment - ongoing medical care is usually required, and benefit is reassessed if treatment restores capacity",
        'severity': "Own Occupation (early years) vs. Any Occupation (often after 24 months)",
        'duration': "Temporary (income protection) vs. Permanent (lump sum)",
        'scope': "Partial/residual disability benefits available on many policies",
        'other': "",
        'impact': "Negatively affects the ability to perform occupational duties or earn an income.",
        'assessment_basis': "Heavily accounts for medication and aids/treatment. Insurers routinely require claimants to undergo and comply with reasonable treatment; if treatment restores capacity to work, benefits can be reduced or terminated. Non-compliance with treatment can itself be grounds for repudiation.",
        'example': "A claimant under an income protection policy is required to continue psychiatric treatment; if medication substantially restores work capacity, the insurer may move the claim from \"totally disabled\" to \"partially disabled\" or decline further benefits.",
        'source': "ASISA (Association for Savings and Investment South Africa) disability definitions; Policyholder Protection Rules (PPR) under the Long-term Insurance Act 52 of 1998",
    },
    {
        'kind': "disability",
        'context': "Insurance - South Africa (Retirement Funds)",
        'term': "Disability",
        'slug': "disability-insurance-south-africa-retirement-funds-disability",
        'family': "insurance",
        'jurisdictions': ['za'],
        'definition': "Physical or mental incapacity of a member which is likely to prevent them from following their normal occupation (or a comparable one) for a period exceeding a fund-specified minimum.",
        'condition': "Physical or mental incapacity of the member exists",
        'functional_status': "The normal or a comparable occupation can't be followed",
        'applied_test': "Trustees weigh actual capacity to work, including with treatment/accommodation",
        'severity': "Total vs. partial incapacity, per fund rules",
        'duration': "Typically requires incapacity expected to exceed a specified minimum period (e.g. 6 months) or be permanent",
        'scope': "Own occupation vs. any comparable occupation, per fund rules",
        'other': "Governed by the Pension Funds Act and the fund's own rules; medical evidence required",
        'impact': "Prevents the member from performing their normal occupation, affecting income and retirement benefits.",
        'assessment_basis': "Fund trustees typically consider the member's actual capacity to work, which includes the effect of treatment and reasonable accommodation, similar to the SSA/employment approach rather than the UK unmitigated approach.",
        'example': "A pension fund's trustees approve an ill-health early retirement benefit only after considering whether reasonable treatment and workplace accommodation could restore the member to work.",
        'source': "Pension Funds Act 24 of 1956 (South Africa)",
    },
    {
        'kind': "disability",
        'context': "Legal - UN (CRPD)",
        'term': "Disability",
        'slug': "disability-legal-un-crpd-disability",
        'family': "legal",
        'jurisdictions': ['comparative'],
        'definition': "Long-term impairments interacting with barriers that hinder full/equal participation.",
        'condition': "A long-term impairment exists",
        'functional_status': "Interaction with societal barriers restricts participation",
        'applied_test': "Aids/meds are \"reasonable accommodations\" the State must provide - the impairment itself is still assessed inherently",
        'severity': "Severity = interaction effect",
        'duration': "Generally >=6 months (\"long-term\")",
        'scope': "Physical, mental, intellectual, or sensory impairments",
        'other': "Ratified by South Africa, UK, and Australia (not directly by the USA)",
        'impact': "Hinders full and effective participation in society on an equal basis with others.",
        'assessment_basis': "Explicitly focuses on barriers, not medical mitigation. Aids/meds are recognised as reasonable accommodations that remove the negative effect, and the State is obligated to provide them, but the underlying impairment itself is assessed inherently.",
        'example': "A country is found in breach of the CRPD for failing to provide sign-language interpreters in courts, regardless of any individual's hearing aid use.",
        'source': "UN Convention on the Rights of Persons with Disabilities (CRPD), Article 1",
    },
    {
        'kind': "disability",
        'context': "Legal - UN (CRPD)",
        'term': "Disablement",
        'slug': "disability-legal-un-crpd-disablement",
        'family': "legal",
        'jurisdictions': ['comparative'],
        'definition': "(Not used)",
        'condition': "N/A",
        'functional_status': "N/A",
        'applied_test': "N/A",
        'severity': "N/A",
        'duration': "N/A",
        'scope': "N/A",
        'other': "N/A",
        'impact': "N/A",
        'assessment_basis': "N/A",
        'example': "N/A",
        'source': "UN Convention on the Rights of Persons with Disabilities (CRPD)",
    },
    {
        'kind': "disability",
        'context': "Insurance (general/international)",
        'term': "Disability",
        'slug': "disability-insurance-general-international-disability",
        'family': "insurance",
        'jurisdictions': ['general'],
        'definition': "Inability to work, triggering income-replacement benefits.",
        'condition': "Illness or injury exists",
        'functional_status': "Occupational duties can't be performed",
        'applied_test': "Own Occupation (early) vs Any Occupation (later) - accounts heavily for treatment",
        'severity': "N/A",
        'duration': "Temporary vs. Permanent",
        'scope': "Own Occupation vs. Any Occupation; Partial (residual) vs. Total",
        'other': "N/A",
        'impact': "Negatively affects the ability to perform occupational duties or earn an income.",
        'assessment_basis': "Heavily accounts for medication and aids. Insurers will typically deny or reduce claims if aids/meds restore the ability to work, especially under \"Any Occupation\" policy definitions. The claimant is only considered disabled if, even with optimal treatment, they cannot work.",
        'example': "A surgeon with a hand tremor is paid under an \"Own Occupation\" definition (cannot operate) but would not qualify under an \"Any Occupation\" definition if able to work in another role.",
        'source': "General international insurance industry practice",
    },
    {
        'kind': "disability",
        'context': "Insurance (general/international)",
        'term': "Disablement",
        'slug': "disability-insurance-general-international-disablement",
        'family': "insurance",
        'jurisdictions': ['general'],
        'definition': "The specific event/claim triggering a payout.",
        'condition': "A specific certifying event/claim arises",
        'functional_status': "Compensation is triggered",
        'applied_test': "Certified only after all reasonable treatments/aids have been tried and failed",
        'severity': "N/A",
        'duration': "N/A",
        'scope': "Permanent Total Disablement (PTD)",
        'other': "Waiting/elimination periods apply",
        'impact': "Triggers financial compensation.",
        'assessment_basis': "Assessed after all reasonable medical treatments and aids have been tried. If aids fail to restore function, disablement is certified.",
        'example': "After a 2-year waiting period and exhausting rehabilitation options, an insurer certifies Permanent Total Disablement and pays the lump sum.",
        'source': "General international insurance industry practice",
    },
    {
        'kind': "disability",
        'context': "Social Security (US - SSA)",
        'term': "Disability",
        'slug': "disability-social-security-us-ssa-disability",
        'family': "legal",
        'jurisdictions': ['comparative'],
        'definition': "Inability to engage in \"Substantial Gainful Activity\" (SGA) due to a medically determinable impairment.",
        'condition': "A medically determinable impairment exists",
        'functional_status': "Substantial Gainful Activity (SGA) can't be sustained",
        'applied_test': "Residual Functional Capacity (RFC) - assessed WITH meds/treatment/aids factored in",
        'severity': "Must be \"severe\"",
        'duration': "\">=12 months or terminal\"",
        'scope': "Cannot earn above the SGA financial threshold",
        'other': "Uses a 5-step sequential evaluation process",
        'impact': "Prevents engagement in any substantial, gainful work.",
        'assessment_basis': "",
        'example': "A claimant's RFC assessment finds that, even with medication, they can only sit for 2 hours a day, supporting a finding of disability.",
        'source': "US Social Security Administration disability criteria",
    },
    {
        'kind': "disability",
        'context': "Social Security (US - SSA)",
        'term': "Disablement",
        'slug': "disability-social-security-us-ssa-disablement",
        'family': "legal",
        'jurisdictions': ['comparative'],
        'definition': "(Not a separate term)",
        'condition': "N/A",
        'functional_status': "N/A",
        'applied_test': "N/A",
        'severity': "N/A",
        'duration': "N/A",
        'scope': "N/A",
        'other': "N/A",
        'impact': "N/A",
        'assessment_basis': "N/A",
        'example': "N/A",
        'source': "US Social Security Administration",
    },
    {
        'kind': "disability",
        'context': "Conceptual / Academic",
        'term': "Disability",
        'slug': "disability-conceptual-academic-disability",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "(See Biopsychosocial and Social model entries above)",
        'condition': "See the Biopsychosocial (ICF) row above",
        'functional_status': "See the Biopsychosocial (ICF) row above",
        'applied_test': "See the Biopsychosocial (ICF) row above",
        'severity': "N/A",
        'duration': "N/A",
        'scope': "N/A",
        'other': "N/A",
        'impact': "N/A",
        'assessment_basis': "(See relevant rows above)",
        'example': "N/A",
        'source': "Disability studies literature",
    },
    {
        'kind': "disability",
        'context': "Conceptual / Academic",
        'term': "Disablement",
        'slug': "disability-conceptual-academic-disablement",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "A metric of functional capacity loss; the process of exclusion.",
        'condition': "Functional capacity loss or an exclusion process exists",
        'functional_status': "Declining functional reserve or increasing exclusion",
        'applied_test': "Capacity (without aids) vs Performance (with aids) separated to isolate the value the aid adds",
        'severity': "N/A",
        'duration': "Rapid-onset vs. Gradual",
        'scope': "Tabular numeric ratings",
        'other': "N/A",
        'impact': "Declining functional reserve or increasing social exclusion.",
        'assessment_basis': "Academic models often explicitly separate capacity (without aids) from performance (with aids) to measure the exact value added by medications and assistive technology.",
        'example': "A researcher compares a cohort's \"capacity-only\" scores against their \"performance-with-assistive-tech\" scores to quantify the value added by the technology.",
        'source': "Disability studies literature",
    },
    {
        'kind': "incapacity",
        'context': "General / Dictionary",
        'term': "Incapacity",
        'slug': "incapacity-general-dictionary-incapacity",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "The state of lacking the physical, mental, or legal ability to do something.",
        'condition': "A physical, mental, or legal limitation exists",
        'functional_status': "An expected act or task can't be performed",
        'applied_test': "Assessed as-is, in the moment - no formal mitigation test",
        'severity': "N/A",
        'duration': "Temporary vs. permanent",
        'scope': "Physical, mental, or legal",
        'other': "Colloquial, non-technical usage",
        'impact': "Prevents a person from performing an act, task, or function they would otherwise be expected to perform.",
        'assessment_basis': "Colloquially assessed as-is (in the person's actual, current state); no formal mitigation test applies.",
        'example': "\"His incapacity after the anaesthetic meant he couldn't sign the form that afternoon.\"",
        'source': "General English usage",
    },
    {
        'kind': "incapacity",
        'context': "Medical Model",
        'term': "Incapacity",
        'slug': "incapacity-medical-model-incapacity",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "Functional inability to perform physical or cognitive tasks due to illness, injury, or impairment.",
        'condition': "Illness, injury, or impairment exists",
        'functional_status': "Specific tasks (work, self-care, decisions) can't be performed",
        'applied_test': "Assessed in the current actual state (with existing treatment); prognosis separately considers future treatment",
        'severity': "Mild to total, often on clinical functional scales",
        'duration': "Acute (short-term) vs. Chronic (ongoing)",
        'scope': "Physical function, cognitive function, or both",
        'other': "Distinguished from \"disability\" by its often acute/episodic framing",
        'impact': "Impairs the ability to perform specific tasks (e.g.",
        'assessment_basis': "Usually assessed in the person's current, actual state (i.e. with whatever treatment they are already on); a separate prognosis considers whether further treatment could restore capacity.",
        'example': "A doctor certifies a patient as temporarily incapacitated for 6 weeks following surgery, pending recovery.",
        'source': "Clinical/medical practice",
    },
    {
        'kind': "incapacity",
        'context': "Employment - South Africa (LRA Schedule 8: Incapacity - Ill Health or Injury)",
        'term': "Incapacity",
        'slug': "incapacity-employment-south-africa-lra-schedule-8-incapacity-ill-health-or-injur",
        'family': "employment",
        'jurisdictions': ['za'],
        'definition': "Inability of an employee to perform their duties due to ill health or injury, which may (if the incapacity is permanent and no reasonable accommodation is possible) constitute a fair reason for dismissal.",
        'condition': "Ill health or injury exists",
        'functional_status': "Duties under the employment contract can't be rendered",
        'applied_test': "Assessed only after the employer has investigated the extent and explored accommodation/alternatives",
        'severity': "Temporary vs. permanent incapacity is the central substantive question",
        'duration': "Nature and extent, and whether it is likely to continue or recur",
        'scope': "Extent to which the employee is able to perform the work; possibility of alternative or adapted work",
        'other': "Distinct from misconduct - dismissal is a \"no-fault\" incapacity process, not a disciplinary one",
        'impact': "Affects the employee's ability to render the services required under the employment contract.",
        'assessment_basis': "The Code of Good Practice on Dismissal requires the employer to investigate the extent of incapacity, consider ways to accommodate the employee short of dismissal (e.g. adapted duties, alternative position, extended sick leave), and consult the employee before considering dismissal — the process, not just the medical state, is central to fairness.",
        'example': "An employee who develops a chronic illness is moved to a lighter-duty role and given extended leave; dismissal is only considered fair once accommodation options are genuinely exhausted and the incapacity is shown to be permanent.",
        'source': "Labour Relations Act 66 of 1995 (South Africa), Schedule 8, Code of Good Practice: Dismissal, items 10-11",
    },
    {
        'kind': "incapacity",
        'context': "Employment - South Africa (LRA Schedule 8: Incapacity - Poor Work Performance)",
        'term': "Incapacity",
        'slug': "incapacity-employment-south-africa-lra-schedule-8-incapacity-poor-work-performan",
        'family': "employment",
        'jurisdictions': ['za'],
        'definition': "Inability of an employee to meet the required performance standard, distinct from ill health, which may justify dismissal if fair procedure (setting standards, training, guidance, evaluation, warning) has been followed.",
        'condition': "A performance shortfall exists",
        'functional_status': "The employer's reasonably required standard isn't met",
        'applied_test': "Assessed against actual performance AFTER guidance, training, and a fair chance to improve",
        'severity': "Degree of shortfall against the set performance standard",
        'duration': "Sustained under-performance despite intervention, not a single lapse",
        'scope': "Specific job requirements/KPIs the employee is failing to meet",
        'other': "Requires proof the standard was reasonable, known to the employee, and consistently applied",
        'impact': "Affects the employee's ability to meet the employer's reasonably required performance standards.",
        'assessment_basis': "Assessed against the employee's actual performance after the employer has provided reasonable guidance, training, counselling, and a fair opportunity to improve — not against an unassisted baseline.",
        'example': "An underperforming sales employee is placed on a formal Performance Improvement Plan with clear targets and coaching before any dismissal for incapacity is considered.",
        'source': "Labour Relations Act 66 of 1995 (South Africa), Schedule 8, Code of Good Practice: Dismissal, item 9",
    },
    {
        'kind': "incapacity",
        'context': "Employment - Australia",
        'term': "Incapacity",
        'slug': "incapacity-employment-australia-incapacity",
        'family': "employment",
        'jurisdictions': ['au'],
        'definition': "Inability of an employee to perform the inherent requirements of their role, relevant to unfair dismissal and workers' compensation claims.",
        'condition': "An impairment exists",
        'functional_status': "Inherent requirements of the role can't be performed",
        'applied_test': "Assessed WITH reasonable adjustments considered first; if none would help, incapacity justifies termination",
        'severity': "N/A",
        'duration': "Temporary vs. permanent incapacity",
        'scope': "\"Inherent requirements\" of the specific position",
        'other': "Interacts with the Disability Discrimination Act 1992 duty to make reasonable adjustments",
        'impact': "Affects the employee's ability to perform the inherent requirements of the job, even with reasonable adjustment.",
        'assessment_basis': "Assessed after considering whether reasonable adjustments would enable the employee to perform the inherent requirements; if no adjustment would help, incapacity to perform inherent requirements can justify termination.",
        'example': "An employer assesses whether modified duties would allow an injured employee to meet the inherent requirements of a role before considering termination.",
        'source': "Fair Work Act 2009 (Cth); Disability Discrimination Act 1992 (Cth)",
    },
    {
        'kind': "incapacity",
        'context': "Insurance (general/international - Income Protection)",
        'term': "Incapacity for Work",
        'slug': "incapacity-insurance-general-international-income-protection-incapacity-for-work",
        'family': "insurance",
        'jurisdictions': ['general'],
        'definition': "The insured's inability, due to illness or injury, to perform the material and substantial duties of their occupation (or, later in a claim, any occupation), triggering income-replacement benefits.",
        'condition': "Illness or injury exists",
        'functional_status': "Material duties of own or any occupation can't be performed",
        'applied_test': "Assessed WITH ongoing treatment as a condition of benefit; reassessed if treatment restores capacity",
        'severity': "Total vs. partial incapacity for work",
        'duration': "Deferred/waiting period, then ongoing while incapacity persists",
        'scope': "Own Occupation (early period) vs. Any Occupation (later period), per policy wording",
        'other': "Often requires the claimant to be \"under the regular care of a medical practitioner\" and following prescribed treatment",
        'impact': "Prevents the claimant from earning income from their occupation.",
        'assessment_basis': "Heavily accounts for treatment and aids: insurers generally require ongoing medical treatment as a condition of benefit, and will reassess (and can reduce/terminate) benefits if treatment restores work capacity — assessed in the treated/mitigated state, similar to the SA income-protection approach.",
        'example': "A claimant's income protection benefit is reviewed after 24 months and moved from an \"Own Occupation\" to an \"Any Occupation\" test, requiring reassessment of whether any suitable work is now possible.",
        'source': "General international income protection/disability insurance policy wording",
    },
    {
        'kind': "incapacity",
        'context': "Workers' Compensation - South Africa (COIDA)",
        'term': "Temporary/Permanent Incapacity",
        'slug': "incapacity-workers-compensation-south-africa-coida-temporary-permanent-incapacit",
        'family': "compensation",
        'jurisdictions': ['za'],
        'definition': "Inability to work resulting from an occupational injury or disease, compensated under COIDA as temporary total, temporary partial, or permanent disablement.",
        'condition': "An occupational injury or disease exists",
        'functional_status': "Ability to earn wages is reduced",
        'applied_test': "Temporary: assessed during recovery. Permanent: only certified at Maximum Medical Improvement",
        'severity': "Total vs. Partial incapacity",
        'duration': "Temporary (during recovery) vs. Permanent (post-MMI)",
        'scope': "Whole-body vs. scheduled body-part impairment, per statutory tables",
        'other': "Compensation Commissioner determines status via medical reports",
        'impact': "Reduces or eliminates the ability to earn wages during the period of incapacity.",
        'assessment_basis': "Temporary incapacity is assessed on the worker's actual current state during recovery/treatment; permanent incapacity is only certified once Maximum Medical Improvement is reached, i.e. after treatment options are exhausted.",
        'example': "An injured worker receives temporary total incapacity payments during six months of treatment, then is assessed for a permanent disablement percentage once stabilised.",
        'source': "Compensation for Occupational Injuries and Diseases Act 130 of 1993 (COIDA), South Africa",
    },
    {
        'kind': "incapacity",
        'context': "Conceptual / Academic",
        'term': "Incapacity",
        'slug': "incapacity-conceptual-academic-incapacity",
        'family': "model",
        'jurisdictions': ['general'],
        'definition': "A broad umbrella concept spanning medical, legal, and functional inability, contrasted with \"disability\" (often more status/rights-based) and \"incapacitation\" (often the active process of losing capacity).",
        'condition': "Varies by discipline - medical, legal, or functional inability",
        'functional_status': "A specific act or decision can't be performed",
        'applied_test': "Modern approach favours decision-specific, functional testing over blanket status labels",
        'severity': "N/A",
        'duration': "N/A",
        'scope': "N/A",
        'other': "Academic usage varies significantly by discipline (law, medicine, sociology, bioethics)",
        'impact': "Varies by discipline; commonly used to denote a functional or legal inability to perform a specific act or decision.",
        'assessment_basis': "Academic and bioethical literature increasingly favours decision-specific, functional tests of incapacity (as in the UK Mental Capacity Act model) over blanket, status-based determinations.",
        'example': "A bioethics paper argues for decision-specific incapacity assessments in hospital consent processes, rather than a single global \"incapacitated\" label.",
        'source': "Bioethics and disability studies literature",
    },
]

FAMILIES = (
    ("model", "How the word is used"),
    ("insurance", "Income protection and insured disability"),
    ("employment", "Workplace incapacity and equity"),
    ("compensation", "Occupational injury schemes"),
    ("legal", "Statute and rights instruments"),
)

def list_definitions(kind: str | None = None, family: str | None = None, juris: str | None = None) -> list[dict]:
    rows = DEFINITIONS
    if kind:
        rows = [r for r in rows if r['kind'] == kind]
    if family:
        rows = [r for r in rows if r['family'] == family]
    if juris and juris not in ('all',):
        rows = [r for r in rows if juris in r['jurisdictions'] or 'general' in r['jurisdictions'] or 'comparative' in r['jurisdictions']]
    return rows

def get_definition(slug: str) -> dict | None:
    for r in DEFINITIONS:
        if r['slug'] == slug:
            return r
    return None

def definition_stats() -> dict[str, int]:
    return {
        'total': len(DEFINITIONS),
        'disability': sum(1 for r in DEFINITIONS if r['kind'] == 'disability'),
        'incapacity': sum(1 for r in DEFINITIONS if r['kind'] == 'incapacity'),
    }

